[package]
name = "jjumper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.8.0"
net = "0.0.2"
bit-set = "0.8.0"
rusb = "0.9.4"
