[package]
name = "bootcore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "0.3.0"
mbrman = "0.5.2"
rusb = "0.9.4"
